### ISSUE TITLE
error: Unknown keyword :type

### ISSUE THREAD

**Issue by tangrammer** [rkaercher/hugsql-ghosts#2]
Hi @rkaercher and thanks for this lib :)

I'm trying to use it following the `MELPA ` installation and adding to my `.emacs.d/init.el` file following lines

```
(require 'hugsql-ghosts)

(add-hook 'cider-mode-hook 'hugsql-ghosts-install-hook)
```

but when i eval init.el buffer i got following error 

```
Warning (initialization): An error occurred while loading `/Users/tangrammer/.emacs.d/init.el':

error: Unknown keyword :type

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

```

Searching a bit I found that the problem could be generated by 
hugsql-ghosts.el LOC=> 54

```
(defface hugsql-ghosts-defn
  '((t :foreground "#686868" :background "#181818"))
  "Face for hugsql defns overlayed when in cider-mode."
  :group 'hugsql-ghosts
  :type 't )

```
Seems that defining faces doesn't allow `:type` https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Faces.html

any ideas to hack this problem?

thanks in advance!

**Comment by rkaercher** [comment]
Hi, @tangrammer,
you're completely right, that keyword does not belong there for deffaces, I was a bit overly excited attaching them to the defcustoms and did not test afterwards in a fresh emacs. I just pushed a commit that removes the keyword so you could either wait for melpa to finish the next build (should be late afternoon/early evening) or just remove the keyword locally until then.
Thanks a lot for reporting the issue!

**Comment by tangrammer** [comment]
Thanks a lot!
